# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

before_script:  
    - git clone https://github.com/ProfesseurPoire/Cabbages-test
    - cd Cabbages-test
    - git checkout develop
    - mkdir build
    - cd build
    - myvar="$PWD"/cabbages-test
    - cmake -DCMAKE_INSTALL_PREFIX=./cabbages-test ..
    - make && make install
    - cd ../../
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX="$myvar" ..

script: make && ctest -V